### ISSUE TITLE
Functions cannot be bound easily

### ISSUE THREAD

**Issue by BobGneu** [BobGneu/Flathead#1]
More info: 

https://groups.google.com/forum/#!topic/v8-users/cYkuljdJEJ8

**Comment by BobGneu** [comment]
From what I was able to piece togther, it looks like updating to a later version (or downgrading to the version used in Node) may be able to address this issue.

**Comment by FREEZX** [comment]
Any news on this?
I think this is essential for having a fully working v8 as a scripting part of UE4.

**Comment by BobGneu** [comment]
Good day, yes. I've been playing with updated versions of v8 for the last few months and will be factoring in some of the changes I've made in order to accommodate the updates. The main issue is that the libraries for v8 64 bit are now upwards of a gig in size and transferring it around is pita. I think I'll have it sorted out soon, but it's not been easy so far. 

will update when I get things stable. Cheers!

**Comment by BobGneu** [comment]
In the next week more information will be available on the fix I have created.
