### ISSUE TITLE
Can’t compile Flathead in VS2013 over UE 4.7, Win 8.1 64bit. error C2065 and error C2661

### ISSUE THREAD

**Issue by AngelTs** [BobGneu/Flathead#5]
Can’t compile Flathead in VS2013 over UE 4.7, Win 8.1 64bit. 
Flathead and v8 are in:
1)f:\UnrealEngine\Engine\Plugins\Flathead\
2)f:\UnrealEngine\Engine\Plugins\Flathead\ThirdParty\v8\
The errors are (in UE4.log):
1)f:\UnrealEngine\Engine\Plugins\Flathead\Source\Flathead\Private\Flathead.cpp(448): error C2065: 'THRESH_VECTORS_ARE_PARALLEL' : undeclared identifier
2)f:\UnrealEngine\Engine\Plugins\Flathead\Source\Flathead\Private\Flathead.cpp(448): error C2661: 'v8::Template::Set' : no overloaded function takes 1 arguments
3)ERROR : UBT error : Failed to produce item: f:\UnrealEngine\Engine\Plugins\Flathead\Binaries\Win64\UE4Editor-Flathead.dll

**Comment by rburnham52** [comment]
Hey, what was the fix for this error?
