### ISSUE TITLE
Working in the Develop branch, where is the source code for FlatheadCore?

### ISSUE THREAD

**Issue by ashleysommer** [BobGneu/Flathead#6]
Is this project abandoned?
I am compiling this module for linux and I need the source code to build Core, where is that?

**Comment by ashleysommer** [comment]
dont worry, I found the newer repo here: https://github.com/OpenGneu/Flathead

**Comment by BobGneu** [comment]
Thanks for finding that. Sorry i didn't notice this sooner =)
